# Generated by Django 3.2.13 on 2022-05-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationCategory',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'applicationscategories',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rights',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rights',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='displayName',
            field=models.CharField(default='Unnamed App', max_length=128),
        ),
        migrations.AddField(
            model_name='applicationcategory',
            name='displayName',
            field=models.CharField(default='Unnamed App', max_length=128),
        ),
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to='core.applicationcategory',
            ),
        ),
        migrations.AddField(
            model_name='userappliction',
            name='right',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to='core.right'
            ),
        ),
    ]
