# Generated by Django 3.2.13 on 2022-05-19 13:17

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        Right = apps.get_model('core', 'Right')
        view_right = Right(id=1, name="View")
        save_right = Right(id=2, name="Save")
        edit_right = Right(id=3, name="Edit")
        delete_right = Right(id=4, name="Delete")
        rights_data = [view_right, save_right, edit_right, delete_right]
        Right.objects.bulk_create(rights_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0003_user_rights'),
    ]

    operations = [migrations.RunPython(insertData)]
