# Generated by Django 3.2.13 on 2022-05-22 07:17

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application Categories to Db
        ApplicationCategory = apps.get_model('core', 'ApplicationCategory')
        supervision_category = ApplicationCategory(
            id=1, name='supervision', displayName='الاشراف|Supervision', icon='server'
        )
        students_category = ApplicationCategory(
            id=2, name='students', displayName='الطلاب|Students', icon='users'
        )
        categories_data = [supervision_category, students_category]
        ApplicationCategory.objects.bulk_create(categories_data, ignore_conflicts=True)
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        import_gs_app = Application(
            id=1,
            name='uploadCDFile',
            displayName='رفع ملف طلاب|Upload Students File',
            icon='cloud-upload',
            category_id=1,
            rights=[1, 2, 3],
        )
        import_inquire_student = Application(
            id=2,
            name='inquireCDStudent',
            displayName='استعلام عن بيانات طلاب الثانوية العامة|High School Student Information',
            icon='info-circle',
            category_id=2,
            rights=[1, 2, 3, 4],
        )
        applictions_data = [import_gs_app, import_inquire_student]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0004_add_system_rights'),
    ]

    operations = [migrations.RunPython(insertData)]
