# Generated by Django 4.0.1 on 2022-07-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_gs_applications'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlList',
            fields=[
                (
                    'control_code',
                    models.IntegerField(
                        db_column='controol_code', primary_key=True, serialize=False
                    ),
                ),
                (
                    'control_name',
                    models.CharField(db_column='controol', max_length=100),
                ),
            ],
            options={
                'db_table': 'controol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EducationalAdministrations',
            fields=[
                (
                    'governorate_code',
                    models.FloatField(
                        db_column='كود المحافظة', primary_key=True, serialize=False
                    ),
                ),
                (
                    'edu_admin_code',
                    models.FloatField(db_column='كود الإدارة التعليمية'),
                ),
                (
                    'edu_admin_name',
                    models.CharField(db_column='الإدارة التعليمية', max_length=400),
                ),
            ],
            options={
                'db_table': 'الادارة',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Governorates',
            fields=[
                (
                    'governorate_code',
                    models.FloatField(
                        db_column='كود المحافظة', primary_key=True, serialize=False
                    ),
                ),
                (
                    'governorate_name',
                    models.CharField(db_column='المحافظة', max_length=400),
                ),
                ('police_code', models.IntegerField(db_column='police_code')),
            ],
            options={
                'db_table': 'المحافظة',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguagesList',
            fields=[
                (
                    'lang_code',
                    models.IntegerField(
                        db_column='lang', primary_key=True, serialize=False
                    ),
                ),
                ('lang_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'اللغات',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NationalityList',
            fields=[
                (
                    'nationality_code',
                    models.IntegerField(
                        db_column='nationality', primary_key=True, serialize=False
                    ),
                ),
                ('nationality_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'الجنسية',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolCodeList',
            fields=[
                ('school_code', models.IntegerField(primary_key=True, serialize=False)),
                (
                    'school_name',
                    models.CharField(db_column='school_code_name', max_length=100),
                ),
            ],
            options={
                'db_table': 'كود_المدرسة',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolTypeList',
            fields=[
                (
                    'school_type_code',
                    models.IntegerField(
                        db_column='type_code', primary_key=True, serialize=False
                    ),
                ),
                (
                    'school_type_name',
                    models.CharField(db_column='type_name', max_length=100),
                ),
                ('flag', models.CharField(max_length=100)),
                ('tolab', models.IntegerField(db_column='TOLAB')),
            ],
            options={
                'db_table': 'school_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StageNew',
            fields=[
                (
                    'seating_no',
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                (
                    'arabic_name',
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                (
                    'school_name',
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ('dept_name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_name', models.CharField(blank=True, max_length=400, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('moslem', models.IntegerField(blank=True, null=True)),
                ('national_no', models.CharField(blank=True, max_length=28, null=True)),
                ('std_type', models.IntegerField(blank=True, null=True)),
                ('branch_code_new', models.IntegerField(blank=True, null=True)),
                ('control_code', models.IntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('moderia', models.CharField(blank=True, max_length=400, null=True)),
                ('nationality', models.IntegerField(blank=True, null=True)),
                ('lang_1', models.IntegerField(blank=True, null=True)),
                ('lang_2', models.IntegerField(blank=True, null=True)),
                ('dept_code', models.IntegerField(blank=True, null=True)),
                ('police_code', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                (
                    'police_station',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ('city_code', models.IntegerField(blank=True, null=True)),
                (
                    'birth_palace',
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ('school_code', models.IntegerField(blank=True, null=True)),
                ('s1', models.FloatField(blank=True, null=True)),
                ('s2', models.FloatField(blank=True, null=True)),
                ('s3', models.FloatField(blank=True, null=True)),
                ('s6', models.FloatField(blank=True, null=True)),
                ('s17', models.FloatField(blank=True, null=True)),
                ('s8', models.FloatField(blank=True, null=True)),
                ('s18', models.FloatField(blank=True, null=True)),
                ('s9', models.FloatField(blank=True, null=True)),
                ('s4', models.FloatField(blank=True, null=True)),
                ('s5', models.FloatField(blank=True, null=True)),
                ('s7', models.FloatField(blank=True, null=True)),
                ('s16', models.FloatField(blank=True, null=True)),
                ('s15', models.FloatField(blank=True, null=True)),
                ('total_degree', models.FloatField(blank=True, null=True)),
                ('s10', models.FloatField(blank=True, null=True)),
                ('s14', models.FloatField(blank=True, null=True)),
                ('s19', models.FloatField(blank=True, null=True)),
                ('no_of_fail', models.IntegerField(blank=True, null=True)),
                ('tanseq_number', models.IntegerField(blank=True, null=True)),
                ('bar_code', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'stagenew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGenderList',
            fields=[
                (
                    'gender_code',
                    models.IntegerField(
                        db_column='male', primary_key=True, serialize=False
                    ),
                ),
                (
                    'gender_name',
                    models.CharField(db_column='male_name', max_length=100),
                ),
            ],
            options={
                'db_table': 'النوع',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentReligionList',
            fields=[
                (
                    'religion_code',
                    models.IntegerField(
                        db_column='moslem', primary_key=True, serialize=False
                    ),
                ),
                (
                    'religion_name',
                    models.CharField(db_column='moslem_name', max_length=100),
                ),
            ],
            options={
                'db_table': 'الديانة',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentsBranchList',
            fields=[
                (
                    'branch_code',
                    models.IntegerField(
                        db_column='branch_code_new', primary_key=True, serialize=False
                    ),
                ),
                (
                    'branch_name',
                    models.CharField(db_column='branch_code_new_name', max_length=100),
                ),
            ],
            options={
                'db_table': 'المجموعة',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='years',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('current', models.IntegerField()),
            ],
            options={
                'db_table': 'years',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semesters',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('current', models.BooleanField()),
                ('tansiqid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'semesters',
            },
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('current', models.BooleanField()),
                ('tansiqid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'stages',
            },
        ),
    ]
