# Generated by Django 4.0.1 on 2022-07-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universities',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=500)),
                ('typeid', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('tansiqid', models.CharField(blank=True, max_length=200, null=True)),
                (
                    'gov_id',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.regions'
                    ),
                ),
            ],
            options={
                'db_table': 'universities',
            },
        ),
    ]
