# Generated by Django 4.0.1 on 2022-07-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
