# Generated by Django 4.0.1 on 2022-07-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_universities_tansiqid'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroups',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('tansiqid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'studygroups',
            },
        ),
    ]
