# Generated by Django 4.0.1 on 2022-07-03 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_gov_id_universities_gov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculties',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                (
                    'facode',
                    models.CharField(
                        blank=True, db_column='faCode', max_length=50, null=True
                    ),
                ),
                ('tansiqid', models.CharField(blank=True, max_length=100, null=True)),
                (
                    'facultyname',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.facultyname',
                    ),
                ),
                (
                    'sector',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.sectors'
                    ),
                ),
                (
                    'studygroup',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.studygroups',
                    ),
                ),
                (
                    'univ',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.universities',
                    ),
                ),
            ],
            options={
                'db_table': 'faculties',
            },
        ),
    ]
