# Generated by Django 3.2.13 on 2022-07-04 06:54

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        import_inquire_student_info = Application(
            id=3,
            name='inquireStudentInfo',
            displayName='استعلام عن بيانات الطلاب|Students Information',
            icon='info-circle',
            category_id=2,
            rights=[1, 3],
        )
        applictions_data = [import_inquire_student_info]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0014_faculties'),
    ]

    operations = [migrations.RunPython(insertData)]
