# Generated by Django 4.0.1 on 2022-07-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_inquireStudentInfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='years',
            options={},
        ),
    ]
