# Generated by Django 4.0.1 on 2022-07-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_certificates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('tansiqid', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
    ]
