# Generated by Django 4.0.1 on 2022-07-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fulfillment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'fulfillment',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'gender',
            },
        ),
        migrations.CreateModel(
            name='ImposedCourses',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'imposedcourses',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'religion',
            },
        ),
        migrations.CreateModel(
            name='SchoolType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'schooltype',
            },
        ),
        migrations.AlterField(
            model_name='facultyname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
