# Generated by Django 4.0.1 on 2022-07-20 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentReligion',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_religion',
                to='core.religion',
            ),
        ),
        migrations.AddField(
            model_name='students',
            name='studentStatus',
            field=models.ForeignKey(
                default=189,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studentStatus',
                to='core.status',
            ),
        ),
    ]
