# Generated by Django 4.0.1 on 2022-07-20 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_students_studentreligion_students_studentstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universities',
            name='gov',
            field=models.ForeignKey(
                default=17,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.regions',
            ),
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
