# Generated by Django 4.0.1 on 2022-07-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_universities_gov_delete_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('studentNID', models.CharField(max_length=14, null=True)),
                ('studentPassport', models.CharField(max_length=25, null=True)),
                ('studentName', models.CharField(max_length=255, null=True)),
                ('studentPhone', models.CharField(max_length=20, null=True)),
                ('studentMail', models.CharField(max_length=100, null=True)),
                ('studentAddress', models.CharField(max_length=200, null=True)),
                ('studentBirthDate', models.DateField(null=True)),
                ('notes', models.TextField(null=True)),
                (
                    'studentAddressPlaceGov',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_add_governorate',
                        to='core.regions',
                    ),
                ),
                (
                    'studentBirthPlaceGov',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_governorate',
                        to='core.regions',
                    ),
                ),
                (
                    'studentGender',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_gender',
                        to='core.gender',
                    ),
                ),
                (
                    'studentNationality',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_nationality',
                        to='core.regions',
                    ),
                ),
                (
                    'studentReligion',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_religion',
                        to='core.religion',
                    ),
                ),
                (
                    'studentStatus',
                    models.ForeignKey(
                        default=189,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='studentStatus',
                        to='core.status',
                    ),
                ),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
