# Generated by Django 4.0.1 on 2022-07-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_studentssecondaryedu'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsUniversityEdu',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('studentTot', models.CharField(max_length=20, null=True)),
                ('studentExpectedGraduationYear', models.IntegerField(null=True)),
                (
                    'studentExpectedGraduationMonth',
                    models.CharField(max_length=20, null=True),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.students'
                    ),
                ),
                (
                    'studentEnrollSemester',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_semester',
                        to='core.semesters',
                    ),
                ),
                (
                    'studentEnrollStage',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_stage',
                        to='core.stages',
                    ),
                ),
                (
                    'studentEnrollYear',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_enroll_year',
                        to='core.years',
                    ),
                ),
                (
                    'studentFaculty',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_faculty',
                        to='core.faculties',
                    ),
                ),
                (
                    'studentUniveristy',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student_university',
                        to='core.universities',
                    ),
                ),
            ],
            options={
                'db_table': 'studentsuniversityedu',
            },
        ),
    ]
