# Generated by Django 4.0.1 on 2022-07-20 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_studentsimposedcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAcceptedApplication',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('studentTot', models.CharField(max_length=200, null=True)),
                ('manualAddition', models.CharField(default=0, max_length=200)),
                (
                    'fac',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='core.faculties',
                    ),
                ),
                (
                    'semester',
                    models.ForeignKey(
                        default=56,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appacc_smester',
                        to='core.semesters',
                    ),
                ),
                (
                    'stage',
                    models.ForeignKey(
                        default=29,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appacc_stage',
                        to='core.stages',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='core.students'
                    ),
                ),
                (
                    'year',
                    models.ForeignKey(
                        default=57,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='appacc_year',
                        to='core.years',
                    ),
                ),
            ],
            options={
                'db_table': 'studentsacceptedapplication',
            },
        ),
    ]
