# Generated by Django 4.0.1 on 2022-07-21 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_studentsacceptedapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentSecondary',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='core.studentssecondaryedu',
            ),
        ),
    ]
