# Generated by Django 4.0.1 on 2022-07-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_studentsuniversityedu_studentsecondary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentsuniversityedu',
            name='studentSecondary',
        ),
    ]
