# Generated by Django 4.0.1 on 2022-07-21 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_studentsuniversityedu_studentsecondary'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='studentFulfillment',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_fulfillment',
                to='core.fulfillment',
            ),
        ),
    ]
