# Generated by Django 4.0.1 on 2022-07-21 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_students_studentfulfillment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentssecondaryedu',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='secondary',
                to='core.students',
            ),
        ),
        migrations.AlterField(
            model_name='studentsuniversityedu',
            name='student',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='university',
                to='core.students',
            ),
        ),
    ]
