# Generated by Django 3.2.13 on 2022-08-03 06:57

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        military_education_app = Application(
            id=4,
            name='militaryEducation',
            displayName='التربية العسكرية|Military Education',
            icon='flag',
            category_id=2,
            rights=[1, 2, 3, 4],
        )
        applictions_data = [military_education_app]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0032_student_model_changes'),
    ]

    operations = [migrations.RunPython(insertData)]
