# Generated by Django 3.2.15 on 2022-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_military_model_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='gender',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schooltype',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='years',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
