# Generated by Django 3.2.13 on 2022-08-10 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220807_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentActualGraduationMonth',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_actual_graduation_month',
                to='core.months',
            ),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentActualGraduationYear',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_actual_graduation_year',
                to='core.years',
            ),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentGraduationGPA',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentGraduationGrade',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_graduation_grade',
                to='core.grades',
            ),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentGraduationPercentage',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
