# Generated by Django 3.2.13 on 2022-08-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_student_uni_edu_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='grades',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='months',
            name='tansiqid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentDivision',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentGraduationProjectGrade',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_graduation_project_grade',
                to='core.grades',
            ),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentSpecialization',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
