# Generated by Django 3.2.13 on 2022-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application Categories to Db
        ApplicationCategory = apps.get_model('core', 'ApplicationCategory')
        graduates_category = ApplicationCategory(
            id=3, name='graduates', displayName='الخرجين|Graduates', icon='users'
        )
        categories_data = [graduates_category]
        ApplicationCategory.objects.bulk_create(categories_data, ignore_conflicts=True)
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        review_graduates_app = Application(
            id=5,
            name='reviewGraduates',
            displayName='مراجعة مرشحين التخرج|Review Graduation Applicants',
            icon='search',
            category_id=3,
            rights=[1, 3],
        )
        applictions_data = [review_graduates_app]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0037_add_missing_fields'),
    ]

    operations = [migrations.RunPython(insertData)]
