# Generated by Django 3.2.15 on 2022-09-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_old_council_id_attr'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('tansiqid', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'oldcouncilid',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                'db_table': 'registrationtype',
            },
        ),
    ]
