# Generated by Django 3.2.15 on 2022-09-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_registrationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('tansiqid', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'oldcouncilid',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                'db_table': 'level',
            },
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentRegistrationType',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_registration_type',
                to='core.registrationtype',
            ),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentLevel',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='student_level',
                to='core.level',
            ),
        ),
    ]
