# Generated by Django 3.2.15 on 2022-09-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20220913_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='totalEquivalentHours',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
