# Generated by Django 3.2.15 on 2022-09-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_studentsuniversityedu_totalequivalenthours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oldcouncilid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
