# Generated by Django 3.2.15 on 2022-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_user_oldcouncilid'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='migration_notes',
            field=models.TextField(null=True),
        ),
    ]
