# Generated by Django 3.2.15 on 2022-09-29 13:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20220927_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'createdAt',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'transactionstype',
            },
        ),
        migrations.CreateModel(
            name='StudentsTransactions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.IntegerField(default=0)),
                (
                    'transactionType',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='transaction_type',
                        to='core.transactionstype',
                    ),
                ),
                ('uniqueId', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255, null=True)),
                ('originalData', models.CharField(max_length=255, null=True)),
                ('updatedData', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'studentstransactions',
            },
        ),
    ]
