# Generated by Django 3.2.15 on 2022-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_graduates_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatesuniversityedu',
            name='transferDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='graduatesuniversityedu',
            name='transferFulfillment',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='transferDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='transferFulfillment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
