# Generated by Django 3.2.13 on 2022-08-30 10:00

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        inquire_graduate_info = Application(
            id=6,
            name='inquireGraduateInfo',
            displayName='استعلام عن بيانات الخرجين|Graduates Information',
            icon='info-circle',
            category_id=3,
            rights=[1, 3],
        )
        applictions_data = [inquire_graduate_info]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0048_auto_20221005_1337'),
    ]

    operations = [migrations.RunPython(insertData)]
