# Generated by Django 3.2.16 on 2022-10-20 11:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_inquire_graduates_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateGroup',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'createdAt',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('sinaiResidentsReduction', models.FloatField(blank=True, null=True)),
                (
                    'semester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='group_semester',
                        to='core.semesters',
                    ),
                ),
                (
                    'stage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='group_stage',
                        to='core.stages',
                    ),
                ),
                (
                    'year',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='group_year',
                        to='core.years',
                    ),
                ),
            ],
            options={
                'db_table': 'certificategroups',
            },
        ),
        migrations.CreateModel(
            name='FacultyProfiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'createdAt',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                (
                    'faculty',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile_faculty',
                        to='core.faculties',
                    ),
                ),
                (
                    'semester',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile_semester',
                        to='core.semesters',
                    ),
                ),
                (
                    'stage',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile_stage',
                        to='core.stages',
                    ),
                ),
                (
                    'year',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='profile_year',
                        to='core.years',
                    ),
                ),
            ],
            options={
                'db_table': 'facultyprofiles',
            },
        ),
        migrations.AddField(
            model_name='registrationtype',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FacultySeatsProfiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'createdAt',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('seats', models.IntegerField()),
                (
                    'certificateGroup',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seats_profile_cert_group',
                        to='core.certificategroup',
                    ),
                ),
                (
                    'facultyProfile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seats_profile_parent',
                        to='core.facultyprofiles',
                    ),
                ),
                (
                    'registrationType',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='seats_profile_reg_type',
                        to='core.registrationtype',
                    ),
                ),
            ],
            options={
                'db_table': 'facultyseatsprofiles',
            },
        ),
        migrations.CreateModel(
            name='FacultyCertProfiles',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'createdAt',
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ('createdBy', models.IntegerField(blank=True, default=0)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('updatedBy', models.IntegerField(null=True)),
                ('minimumDegree', models.FloatField()),
                (
                    'certificate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cert_profile_cert',
                        to='core.certificates',
                    ),
                ),
                (
                    'certificateGroup',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cert_profile_cert_group',
                        to='core.certificategroup',
                    ),
                ),
                (
                    'certificateYear',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cert_profile_cert_year',
                        to='core.years',
                    ),
                ),
                (
                    'facultyProfile',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cert_profile_parent',
                        to='core.facultyprofiles',
                    ),
                ),
            ],
            options={
                'db_table': 'facultycertprofiles',
            },
        ),
        migrations.CreateModel(
            name='CertificateGroupRelations',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.IntegerField(default=0)),
                (
                    'certificate',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='related_certificate',
                        to='core.certificates',
                    ),
                ),
                (
                    'certificateGroup',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='related_certificate_group',
                        to='core.certificategroup',
                    ),
                ),
            ],
            options={
                'db_table': 'certificategrouprelations',
            },
        ),
    ]
