# Generated by Django 3.2.16 on 2022-10-26 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_auto_20221020_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatesuniversityedu',
            name='pathShiftDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='pathShiftDate',
            field=models.DateField(null=True),
        ),
    ]
