# Generated by Django 3.2.16 on 2022-10-29 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20221029_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatesuniversityedu',
            name='transferFulfillment',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='graduatesuniversityedu_fulfillment',
                to='core.fulfillment',
            ),
        ),
        migrations.AlterField(
            model_name='studentsuniversityedu',
            name='transferFulfillment',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studentsuniversityedu_fulfillment',
                to='core.fulfillment',
            ),
        ),
    ]
