# Generated by Django 3.2.16 on 2022-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_20221029_transferFulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatesimposedcourses',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentsimposedcourses',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
