# Generated by Django 3.2.16 on 2022-11-03 12:37

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application Categories to Db
        ApplicationCategory = apps.get_model('core', 'ApplicationCategory')
        report_category = ApplicationCategory(
            id=4, name='reports', displayName='التقارير|Reports', icon='chart-bar'
        )
        categories_data = [report_category]
        ApplicationCategory.objects.bulk_create(categories_data, ignore_conflicts=True)
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        import_gs_app = Application(
            id=8,
            name='numberAcceptedStudents',
            displayName='أعداد الطلاب المقبولين بالجامعات|Number of accepted students in universities',
            icon='file',
            category_id=4,
            rights=[1],
        )
        applictions_data = [import_gs_app]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0054_imposed_course_completed'),
    ]

    operations = [migrations.RunPython(insertData)]
