# Generated by Django 3.2.16 on 2022-11-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_count_report_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatesuniversityedu',
            name='studentCustomUniversityFaculty',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentCustomUniversityFaculty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
