# Generated by Django 3.2.16 on 2022-12-04 09:37

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        review_initially_accepted = Application(
            id=9,
            name='reviewInitiallyAccepted',
            displayName='مراجعة المقبولين مبدئيا|Review Initially Accepted Students',
            icon='search',
            category_id=2,
            rights=[1, 3],
        )
        applictions_data = [review_initially_accepted]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0056_custom_univ_fac_field'),
    ]

    operations = [migrations.RunPython(insertData)]
