# Generated by Django 3.2.16 on 2022-12-05 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_review_initially_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduatesmilitaryedu',
            name='militaryEduMonth',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='graduatesmilitaryedu_month',
                to='core.months',
            ),
        ),
        migrations.AddField(
            model_name='graduatesuniversityedu',
            name='studentGraduationEquivalentHours',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentsmilitaryedu',
            name='militaryEduMonth',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='studentsmilitaryedu_month',
                to='core.months',
            ),
        ),
        migrations.AddField(
            model_name='studentsuniversityedu',
            name='studentGraduationEquivalentHours',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
