# Generated by Django 3.2.16 on 2022-12-06 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_adds_ts_requested_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('createdBy', models.IntegerField(default=0)),
                ('uniqueId', models.CharField(max_length=255)),
                ('attachmentId', models.CharField(max_length=50, null=True)),
                ('filename', models.CharField(max_length=500, null=True)),
                ('mimetype', models.CharField(max_length=30, null=True)),
            ],
            options={
                'db_table': 'studentsattachments',
            },
        ),
    ]
