# Generated by Django 3.2.16 on 2022-12-13 08:53

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        uni_statistics_app = Application(
            id=11,
            name='universityStatusStatistics',
            displayName='أعداد الطلاب المقبولين و تحت الاستيفاء والمرفوضين|Number of accepted, under fulfillment and rejected students',
            icon='file',
            category_id=4,
            rights=[1],
        )
        applictions_data = [uni_statistics_app]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0059_studentsattachments'),
    ]

    operations = [migrations.RunPython(insertData)]
