# Generated by Django 3.2.16 on 2022-12-21 14:54

from django.db import migrations


class Migration(migrations.Migration):
    def insertData(apps, schema_editor):
        # Adds new Application To Db
        Application = apps.get_model('core', 'Application')
        names_report_app = Application(
            id=10,
            name='acceptedStudentsNames',
            displayName='أسماء الطلاب المقبولين|Names of Accepted Students',
            icon='file',
            category_id=4,
            rights=[1],
        )
        transfer_report_app = Application(
            id=12,
            name='transferStudentsStatistics',
            displayName='اعداد الطلاب المحولين|Number of Transferred Students',
            icon='file',
            category_id=4,
            rights=[1],
        )
        define_universities_app = Application(
            id=13,
            name='defineUniversities',
            displayName='تعريف الجامعات|Define Universities',
            icon='plus-circle',
            category_id=1,
            rights=[1, 2, 3, 4],
        )
        define_faculties_app = Application(
            id=14,
            name='defineFaculties',
            displayName='تعريف الكليات|Define Faculties',
            icon='plus-circle',
            category_id=1,
            rights=[1, 2, 3, 4],
        )
        define_certificates_app = Application(
            id=15,
            name='defineCertificates',
            displayName='تعريف الشهادات|Define Certificates',
            icon='plus-circle',
            category_id=1,
            rights=[1, 2, 3, 4],
        )
        define_certificate_groups_app = Application(
            id=16,
            name='defineCertificateGroups',
            displayName='تعريف مجموعات الشهادات|Define Certificate Groups',
            icon='plus-circle',
            category_id=1,
            rights=[1, 2, 3, 4],
        )
        applictions_data = [
            names_report_app,
            transfer_report_app,
            define_universities_app,
            define_faculties_app,
            define_certificates_app,
            define_certificate_groups_app,
        ]
        Application.objects.bulk_create(applictions_data, ignore_conflicts=True)

    dependencies = [
        ('core', '0060_uni_accepted_stats_report'),
    ]

    operations = [migrations.RunPython(insertData)]
